[package]
name = "interpreter"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
plonky2 = "1.0.2"
rand = "0.9.0"
serde = "1.0.218"
bitvec = "1.0"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "hashmap_benchmark2"
harness = false